### ISSUE TITLE
2017 T-shirt候选设计

### ISSUE THREAD

**Issue by philipxyc** [ShanghaitechGeekPie/DailyWork#3]
以下是筛选过后的11份筛选，请大家按自己喜好选择。
投票设在[GeekPie科创工作室群]内，请进群投票。
投票不限个数

1
![qq 20170905153541](https://user-images.githubusercontent.com/12481493/30051060-3a2d67f8-9253-11e7-9f46-d2363acf5eaa.jpg)

2
![qq 20170905153405](https://user-images.githubusercontent.com/12481493/30051062-3a32485e-9253-11e7-953f-5cc911ca1438.jpg)

3
![86595ace114e09c867ed111b7e8f1ec0](https://user-images.githubusercontent.com/12481493/30051058-3a21993c-9253-11e7-9caa-dbdb45108317.jpg)

4
![6609ce8db48975d5704ce58fc38eafd5](https://user-images.githubusercontent.com/12481493/30051068-3a83e56a-9253-11e7-94c5-8def61f67555.jpg)

5
![50d0c395844bd8b9076a7708dd560970](https://user-images.githubusercontent.com/12481493/30051067-3a6742fc-9253-11e7-9530-5ac1475fec91.jpg)

6
![46dbac04bfeac8d8b213617622da33ce](https://user-images.githubusercontent.com/12481493/30051066-3a608714-9253-11e7-932a-0cdb3ca04672.jpg)

7
![6c400eb58224a0082eec592578dabe71](https://user-images.githubusercontent.com/12481493/30051065-3a6068c4-9253-11e7-8965-173005547711.jpg)

8
![-2d8f29aacd24262f](https://user-images.githubusercontent.com/12481493/30051064-3a5b8cc8-9253-11e7-870e-6031c0913989.jpg)

9
![0f66b5f3038cc3c3aaaf79c050a57de9](https://user-images.githubusercontent.com/12481493/30051063-3a4fdffe-9253-11e7-868d-b939ca9292b8.jpg)

10
![qq 20170905153604](https://user-images.githubusercontent.com/12481493/30051059-3a2b946e-9253-11e7-8335-455193d6d330.jpg)

11
![geek piet 1](https://user-images.githubusercontent.com/12481493/30051061-3a2d8ab2-9253-11e7-8cbb-e3a1eed5769d.png)

**Comment by lijialun123** [comment]
我选10

**Comment by yuehaowang** [comment]
我选1吧

**Comment by wch930** [comment]
我也选1

**Comment by wtlyu** [comment]
FINISHED

**Comment by yuehaowang** [comment]
结果多久公布呀？

**Comment by wtlyu** [comment]
已经确定，正在和供应商确认价格和工艺

**Comment by yuehaowang** [comment]
不是geekpie的新萌可以领吗？🙃

**Comment by wtlyu** [comment]
可以
