### ISSUE TITLE
请求贵站加入 mirrorz.org

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [ShanghaitechGeekPie/DailyWork#8]
最近开发一个项目 https://github.com/tuna/mirrorz ，目的是将各个镜像站的信息汇总起来，形成类似黄页的东西，不知道贵站是否有兴趣加入该项目

Demo: [www.mirrorz.org](https://www.mirrorz.org)

**Comment by LoganJoe** [comment]
很好啊，欢迎欢迎！相关信息我们稍后给出。

**Comment by ZenithalHourlyRate** [comment]
目前 https://mirrorz.org 有了全新的前端，特此供贵站参考。

**Comment by ZenithalHourlyRate** [comment]
目前可以不由贵站提供 `mirrorz.json` ，只需提供同步状态数据（ https://mirrors-wan.geekpie.club/Mirrors-Status.json ）的跨域访问

具体方法为添加 `Access-Control-Allow-Origin: *` 的头或者（在`referer: https://mirrorz.org/`时）添加 `Access-Control-Allow-Origin: https://mirrorz.org`

参考 https://github.com/PKUOSC/issues/issues/2

**Comment by ZenithalHourlyRate** [comment]
https://github.com/mirrorz-org/mirrorz-parser/commit/1e92b2a52106261e3817ceb0856765af58a7edcb
https://github.com/mirrorz-org/mirrorz-config/commit/933156b1666092e4526ec84c2d694a3ce18bcf16
